---
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 200
  code_blocks: true
  tables: false
  headings: true
  strict: true
  stern: true
MD033:
  allowed_elements: [details, summary, br, b, i]
