---
name: Docs
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths: [README.md]
concurrency:
  group: |
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Generate docs
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v3.0.6
        with:
          vimdoc: remote-nvim
          version: Neovim >= 0.8.0
          demojify: true
          treesitter: true
          dedupsubheadings: false
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: 'chore(build): auto-generate vimdoc'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: |-
            github-actions[bot] <github-actions[bot]@users.noreply.github.com>
