---
name: Release
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
concurrency:
  group: |
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: Generate release
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: remote-nvim.nvim
          include-v-in-tag: true
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          pull-request-title-pattern: 'chore: release ${version}'
          extra-files: |-
            lua/remote-nvim/init.lua
